---
abstract: 'make a Dancer app mobile-aware'
author:
  - 'Dancer Core Developers'
build_requires:
  Dancer::Test: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-MobileDevice
provides:
  Dancer::Plugin::MobileDevice:
    file: lib/Dancer/Plugin/MobileDevice.pm
    version: '0.04'
requires:
  Dancer: '0'
  Dancer::Plugin: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/PerlDancer/Dancer-Plugin-MobileDevice/issues
  homepage: http://perldancer.org/
  repository: https://github.com/PerlDancer/Dancer-Plugin-MobileDevice
version: '0.04'
x_serialization_backend: 'YAML::Tiny version 1.67'
